apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: app1-ns
spec:
  type: ClusterIP
  selector:
    app: 05-Projects/app1-frontend-config/frontend
  ports:
    - port: 80
      targetPort: 4000
